version: '3'
services:
  db:
    container_name: ctoip_db
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - net_ctoip
  redis:
    container_name: ctoip_redis
    image: redis:7.0.9
    command: [ "redis-server", "--appendonly", "yes", "--requirepass","root" ]
    ports:
      - "6379:6379"
    networks:
      - net_ctoip
  nginx:
    depends_on:
      - db
      - redis
      - spring
    container_name: ctoip_vue
    build:
      context: .
      dockerfile: Dockerfile.web
    environment:
      SERVERIP: ctoip_spring
    ports:
      - "80:80"
    networks:
      - net_ctoip
  spring:
    depends_on:
      - db
      - redis
    container_name: ctoip_spring
    build:
      context: .
      dockerfile: Dockerfile.spring
    environment:
      MYSQLIP: ctoip_db
      REDISIP: ctoip_redis
    ports:
      - "8081:8081"
    networks:
      - net_ctoip
networks:
  net_ctoip:
    driver: bridge
